# There are GitLab projects, whose repos are not meant to be cloned.
# Code in these repos is synched with corresponding subdirs of the [CMagneto project](https://gitlab.com/dishsoftware/cmagneto) repo
# and is pushed by a CMagneto CI Bot.
#
# Each of these test projects serves just as:
# 1) Registry of Docker images, related to the test project;
# 2) Runner of CI jobs, related to the test project;
# 3) Package registry for built installation packages of the test project.


stages:
  - run_unit_and_integration_tests
  # Seed project is in './ProjectRoot/'. Its pipelines are run according to the pipeline wokflow.
  - trigger__seed_project__pipeline
  - wait__seed_project__pipeline

  # Test projects are in './tests/system/testProjects/'. Their pipelines are run only if there is a push into 'main'.
  # - trigger__test_projects__pipelines
  # - wait__test_projects__pipelines


JOB~run_unit_and_integration_tests:
  stage: run_unit_and_integration_tests

  # Run `./CI/Docker/build_image__unit_and_integration_tests.py` to build and push the image.
  image: registry.gitlab.com/dishsoftware/cmagneto/unit_and_integration_tests:1.0.0

  script:
    - python3 ./tests/run_unit_and_integration_tests.py
  artifacts:
    when: always
    reports:
      junit: ./tests/summary/pytest-report.xml
    paths:
      - ./tests/summary/
    expire_in: 30 days


JOB~sync__seed_project__to__seed_project_repo: # Prefix 'JOB~' to be consistent with 'JOB~trigger__seed_project__pipeline', etc.
  stage: trigger__seed_project__pipeline
  needs:
  - job: JOB~run_unit_and_integration_tests
    artifacts: false

  # Run `./CI/Docker/build_image__for_repo_shenanigans.py` to build and push the image.
  image: registry.gitlab.com/dishsoftware/cmagneto/for_repo_shenanigans:1.0.0

  before_script:
    # "Source" the script, because otherwise the SSH-setup is done in a child process and has no effect on the job.
    - source ./CI/GitLab/add__test_project__private_key__to_ssh_agent.sh "CMAGNETO_CI_BOT__PRIVATE_SSH_KEY_BASE64__FOR_SEED_PROJECT_REPO"
  script:
    - python3 ./CI/GitLab/sync__test_projectroot__to__test_project_repo.py "ProjectRoot/" "git@gitlab.com:dishsoftware/contactholder.git"


JOB~trigger__seed_project__pipeline: # Prefix 'JOB~' to not confuse the job with the stage.
  stage: trigger__seed_project__pipeline
  needs:
    - job: JOB~sync__seed_project__to__seed_project_repo
      artifacts: false
  trigger:
    project: dishsoftware/contactholder
    branch: $CI_COMMIT_REF_NAME
    strategy: depend


JOB~wait__seed_project__pipeline:    # Prefix 'JOB~' to not confuse the job with the stage.
  stage: wait__seed_project__pipeline
  needs:
    - job: JOB~trigger__seed_project__pipeline
      artifacts: false
  script:
    - echo "Seed project pipeline has finished."