FROM python:3-slim

# Avoid interactive prompts during installs.
ENV DEBIAN_FRONTEND=noninteractive

# Install dependencies and dev tools.
RUN apt-get update && apt-get install -y --no-install-recommends \
        python-is-python3 \
        tree \
    && apt-get clean

WORKDIR /project