FROM debian:12

# Metadata
LABEL version="1.0.0"

# Avoid interactive prompts during installs.
ENV DEBIAN_FRONTEND=noninteractive

# Install dependencies and dev tools.
RUN apt update && apt install -y \
    git \
    python3 \
    python-is-python3 \
    build-essential \
    cmake \
    graphviz \
    qt6-base-dev \
    libboost-all-dev \
    dpkg-dev \
    && apt clean

WORKDIR /project
